changelog:
  categories:
    - title: "Breaking Changes"
      labels:
        - "breaking-change"
    - title: "Features & Enhancements"
      labels:
        - "enhancement"
    - title: "Security Fixes"
      labels:
        - "security"
    - title: "Bug Fixes"
      labels:
        - "bug"
    - title: "Documentation"
      labels:
        - "documentation"
    - title: "Dependency Updates"
      labels:
        - "dependencies"
    - title: "Other Changes"
      labels:
        - "*"